version: '3'
services:
  node:
    build: transnet-core
    container_name: node
    ports:
     - "9090:9090"
     - "8090:8090"
    expose:
     - "8090"
     - "9090"
    volumes:
     - "../data_witness_node:/data_witness_node"
  faucet:
    build: faucet
    container_name: faucet
    expose:
     - "9090"
  ui:
     build: transnet-ui
     container_name: ui
  witness:
    build: transnet-witness
    container_name: witness
  nginx:
    build: nginx
    container_name: nginx
    ports:
     - "80:80"
