version: '3'
services:
  node:
    build: transnet-core
    container_name: node
    ports:
     - "9090:9090"
    expose:
     - "8090"
    volumes:
     - "node_data:/data_witness_node"
  faucet:
    build: faucet
    container_name: faucet
    expose:
     - "9090"
  # wallet:
  #   build: transnet-ui
  #   container_name: wallet
  witness:
    build: transnet-witness
    container_name: witness
  nginx:
    build: nginx
    container_name: nginx
    ports:
     - "80:80"
    volumes:
     - "./wallet:/www/current/"
volumes:
  node_data: {}
