### CHANGE "/path_to_data/" AND "/path_to_cert/" WITH REAL PATHS!!! ###

version: '3'
services:
  node:
    build: transnet-core
    container_name: node
    ports:
     - "9090:9090"
    expose:
     - "8090"
    volumes:
     - "/path_to_data/:/data_witness_node"
  faucet:
    build: faucet
    container_name: faucet
    expose:
     - "9090"
  # wallet:
  #   build: transnet-ui
  #   container_name: wallet
  witness:
    build: transnet-witness
    container_name: witness
  nginx:
    build: nginx
    container_name: nginx
    ports:
     - "10443:443"
    volumes:
     - "./wallet:/www/current/"
     - "/path_to_cert/:/www/cert/"
# volumes:
#  node_data: {}
